services:
    _defaults:
        public: true

    oro_test.alice_fixture_loader:
        class: Oro\Bundle\TestFrameworkBundle\Test\DataFixtures\AliceFixtureLoader
        arguments:
            - '@oro_test.fixture_loader.doctrine.purger_loader'
            - '@file_locator'

    oro_test.fixture_loader.doctrine.purger_loader:
        class: Fidry\AliceDataFixtures\Loader\PurgerLoader
        lazy: true
        arguments:
            - '@oro_test.fixture_loader.doctrine.persister_loader'
            - '@fidry_alice_data_fixtures.persistence.purger_factory.doctrine'
            - 'no_purge'

    fidry_alice_data_fixtures.persistence.purger_factory.doctrine:
        class: 'Fidry\AliceDataFixtures\Bridge\Doctrine\Purger\Purger'
        lazy: true
        arguments:
            - '@doctrine.orm.entity_manager'

    oro_test.fixture_loader.doctrine.persister_loader:
        class: 'Fidry\AliceDataFixtures\Loader\PersisterLoader'
        lazy: true
        arguments:
            - '@oro_test.fixture_loader.alice_combined_loader'
            - '@fidry_alice_data_fixtures.persistence.persister.doctrine'

    fidry_alice_data_fixtures.persistence.persister.doctrine:
        class: 'Fidry\AliceDataFixtures\Bridge\Doctrine\Persister\ObjectManagerPersister'
        lazy: true
        arguments:
            - '@doctrine.orm.entity_manager'

    oro_test.fixture_loader.alice_combined_loader:
        class: 'Oro\Bundle\TestFrameworkBundle\Test\DataFixtures\Loader\AliceCombinedLoader'
        lazy: true
        arguments:
            - '@nelmio_alice.files_loader.simple'
            - '@nelmio_alice.data_loader.simple'
