services:
    _defaults:
        public: true

#    # vendor/nelmio/alice/src/Bridge/Symfony/Resources/config/loader.xml
#
#    nelmio_alice.data_loader:
#        alias: 'nelmio_alice.data_loader.simple'
#
#    nelmio_alice.data_loader.simple:
#        class: 'Nelmio\Alice\Loader\SimpleDataLoader'
#        arguments:
#            - '@nelmio_alice.fixture_builder'
#            - '@nelmio_alice.generator'
#
#    nelmio_alice.file_loader:
#        alias: 'nelmio_alice.file_loader.simple'
#
#    nelmio_alice.file_loader.simple:
#        class: 'Nelmio\Alice\Loader\SimpleFileLoader'
#        arguments:
#            - '@nelmio_alice.file_parser'
#            - '@nelmio_alice.data_loader'
#
#    nelmio_alice.files_loader:
#        alias: 'nelmio_alice.files_loader.simple'
#
#    nelmio_alice.files_loader.simple:
#        class: 'Nelmio\Alice\Loader\SimpleFilesLoader'
#        arguments:
#            - '@nelmio_alice.file_parser'
#            - '@nelmio_alice.data_loader'
#
#    # vendor/nelmio/alice/src/Bridge/Symfony/Resources/config/fixture_builder/main.xml
#    nelmio_alice.fixture_builder:
#        alias: 'nelmio_alice.fixture_builder.simple'
#
#    nelmio_alice.fixture_builder.simple:
#        class: 'Nelmio\Alice\FixtureBuilder\SimpleBuilder'
#        arguments:
#            - '@nelmio_alice.fixture_builder.denormalizer'
#
#    nelmio_alice.fixture_builder.denormalizer:
#        alias: 'nelmio_alice.fixture_builder.denormalizer.simple'
#
#    nelmio_alice.fixture_builder.denormalizer.simple:
#        class: 'Nelmio\Alice\FixtureBuilder\Denormalizer\SimpleDenormalizer'
#        arguments:
#            - '@nelmio_alice.fixture_builder.denormalizer.parameter_bag'
#            - '@nelmio_alice.fixture_builder.denormalizer.fixture_bag'
#
#    nelmio_alice.fixture_builder.denormalizer.parameter_bag:
#        alias: 'nelmio_alice.fixture_builder.denormalizer.parameter.simple_parameter_bag_denormalizer'
#
#    nelmio_alice.fixture_builder.denormalizer.parameter.simple_parameter_bag_denormalizer:
#        class: 'Nelmio\Alice\FixtureBuilder\Denormalizer\Parameter\SimpleParameterBagDenormalizer'
#
#    # vendor/nelmio/alice/src/Bridge/Symfony/Resources/config/generator/main.xml
#
#    nelmio_alice.generator:
#        alias: 'nelmio_alice.generator.double_pass'
#
#    nelmio_alice.generator.double_pass:
#        class: 'Nelmio\Alice\Generator\DoublePassGenerator'
#        arguments:
#            - '@nelmio_alice.generator.resolver.fixture_set'
#            - '@nelmio_alice.generator.object_generator'
#
#    nelmio_alice.generator.object_generator:
#        alias: 'nelmio_alice.generator.object_generator.complete'
#
#    nelmio_alice.generator.object_generator.complete:
#        class: 'Nelmio\Alice\Generator\ObjectGenerator\CompleteObjectGenerator'
#        arguments:
#            - '@nelmio_alice.generator.object_generator.simple'
#
#    nelmio_alice.generator.object_generator.simple:
#        class: 'Nelmio\Alice\Generator\ObjectGenerator\SimpleObjectGenerator'
#        arguments:
#            - '@nelmio_alice.generator.resolver.value'
#            - '@nelmio_alice.generator.instantiator'
#            - '@nelmio_alice.generator.hydrator'
#            - '@nelmio_alice.generator.caller'
#
#    # vendor/nelmio/alice/src/Bridge/Symfony/Resources/config/parser.xml
#
#    nelmio_alice.file_parser:
#        alias: 'nelmio_alice.file_parser.runtime_cache'
#
#    nelmio_alice.file_parser.runtime_cache:
#        class: 'Nelmio\Alice\Parser\RuntimeCacheParser'
#        arguments:
#            - '@nelmio_alice.file_parser.registry'
#            - '@nelmio_alice.file_locator'
#            - '@nelmio_alice.file_parser.default_include_processor'
#
#
#    nelmio_alice.file_parser.symfony_yaml:
#        class: 'Symfony\Component\Yaml\Parser'
#
#    nelmio_alice.file_parser.default_include_processor:
#        class: 'Nelmio\Alice\Parser\IncludeProcessor\DefaultIncludeProcessor'
#        arguments:
#            - '@nelmio_alice.file_locator'
#
#
#    nelmio_alice.file_parser.registry:
#        class: 'Nelmio\Alice\Parser\ParserRegistry'
#        arguments:
#            - !tagged nelmio_alice.file_parser
#
#    nelmio_alice.file_parser.chainable.yaml:
#        class: 'Nelmio\Alice\Parser\Chainable\YamlParser'
#        arguments:
#            - '@nelmio_alice.file_parser.symfony_yaml'
#        tags:
#            - { name: nelmio_alice.file_parser }
#
#    nelmio_alice.file_parser.chainable.php:
#        class: 'Nelmio\Alice\Parser\Chainable\PhpParser'
#        tags:
#            - { name: nelmio_alice.file_parser }
#
#    nelmio_alice.file_parser.chainable.json:
#        class: 'Nelmio\Alice\Parser\Chainable\JsonParser'
#        tags:
#            - { name: nelmio_alice.file_parser }
#
